import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

/** @type {import("esbuild").BuildOptions} */
const options = {
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    // Obsidian and its bundled CodeMirror/Electron modules are provided by the
    // host at runtime; bundling them would duplicate the app's own copies.
    external: ["obsidian", "electron", "@codemirror/*", ...builtins],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    // Map tile/marker assets pulled in by CSS are inlined so the plugin stays a
    // self-contained main.js + styles.css pair with no loose asset files.
    loader: { ".png": "dataurl", ".svg": "dataurl" },
};

// esbuild 0.17 removed the `watch` build option in favour of the context API.
if (prod) {
    await esbuild.build(options);
} else {
    const ctx = await esbuild.context(options);
    await ctx.watch();
}
